# Generated by Django 3.1.7 on 2021-03-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Currency name')),
                ('rate', models.FloatField(verbose_name='Currency rate to Rouble')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
