# Generated by Django 3.1.7 on 2021-03-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Currency name'),
        ),
    ]
