# Generated by Django 3.1.7 on 2021-03-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20210324_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
